# Generated by Django 5.1.4 on 2025-01-09 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recomender_apis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("sex", models.CharField(max_length=10)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("profesor", "Profesor"),
                            ("estudiante", "Estudiante"),
                            ("cliente", "Cliente"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="qualitydata",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recomender_apis.user"
            ),
        ),
    ]
