# Generated by Django 5.1.4 on 2025-01-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recomender_apis", "0002_user_alter_qualitydata_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
